@startuml
title AI Workflows


json HostedModels {
    "Language":[
        "LLama",
        "GPT-4o"
    ],
    "Audio/Speech":[
        "Whisper",
        "AudioLDM",
        "MusicGen"
    ],
    "Video":[
        "Sora",
        "Lumiere",
        "Gen-2"
    ],
    "Multimodal":[
        "GPT-4V",
        "Opus",
        "Gemini Pro Vision"
    ],
    "3dGen":[
        "Point-E",
        "GET3D",
        "Shap-E"
    ],
    "Code":[
        "CoPilot"
    ]   
}




rectangle "AI Ops" {
rectangle "AI Pipeline"{
    queue "feature pipeline" as featurePipe
    queue "training pipeline" as training
    queue "inference pipeline" as inference
json OnPremModels {
    "Language":[
        "LLama",
        "Deepseek"
    ],

    "Code":[
        "CoPilot",
        "Code Llama"
    ],
    "Biochem":[
        "AlphaFold",
        "RoseTTAFold",
        "ESMFold"
    ],
    "Graph":[
        "GraphTransformer",
        "GraphGPS",
        "GIANT"
    ],
    "Time Series":[
        "TFT",
        "N-BEATS",
        "TimeGPT"
    ],
    "Reinforcement":[
        "Muzero",
        "Gato"
    ]    
}
}

json Outcomes {
    "Generative":[
        "Code Generation",
        "Chatbot",
        "Assistive Design",
        "Data Creation"
        ],
    "Agentic":[
        "Chat Agent",
        "Digital Assitant"
    ],
    "Autonomous/Assistive":[
        "Computer Vision",
        "Digital Twin",
        "Voice Processing"
    ]
}
}

rectangle "Operational Data" {
    database "sales" as salesdata
    database "supplier" as supplierdata
    database "message" as message
    database "support" as support
    database "ops" as ops
    rectangle "unstructured data" as unstructured
    rectangle "structured data" as structured    
    file "file" as file   
}



unstructured -right-> featurePipe
structured -right-> featurePipe
featurePipe --> training
training --> inference
salesdata --> structured
supplierdata --> structured
message --> unstructured
support --> unstructured
file --> unstructured
ops --> unstructured
ops --> structured

HostedModels --> Outcomes
inference --> OnPremModels
OnPremModels --> Outcomes



@enduml