@startsalt
{
{^==Widget
 Note on top
 <img:https://plantuml.com/logo3.png>
}|
    {^==Widget
note
 <img:https://plantuml.com/logo3.png>
}


{^==Widget
 second row first column
 <img:https://plantuml.com/logo3.png>
}|
  {^==Widget
 second row 2nd column
 <img:https://plantuml.com/logo3.png>
}
}

@endsalt
