@startuml
!pragma teoz true
    participant author
    queue collab as "research\nrepo"
    participant stakeholder
    queue "Project Mgmt\nSystem"
    participant approver

group collaborative authoring
    author --> collab : create artifact
    author --> stakeholder : "please review"
    stakeholder --> collab : review and\ncomment
    author --> collab : edit
end group

group backlog refinement
    author --> collab
        &collab --> "Project Mgmt\nSystem" 
    approver --> "Project Mgmt\nSystem" : review
    approver <--> stakeholder : confer
    approver --> "Project Mgmt\nSystem" : comment
    author --> "Project Mgmt\nSystem" : edit
    approver --> "Project Mgmt\nSystem" : approve
end group
@enduml
