@startsalt

{+Unicode box drawing                                                                                                        
    ─	━	│	┃	┄	┅	┆	┇	┈	┉	┊	┋ 
┌	┍	┎	┏	┐	┑	┒	┓	└	┕	┖	┗
┘	┙	┚	┛	├	┝	┞	┟	┠	┡	┢	┣
┤	┥	┦	┧	┨	┩	┪	┫	┬	┭	┮
	┯
┰	┱	┲	┳	┴	┵	┶	┷	┸	┹	┺	┻
┼	┽	┾	┿	╀	╁	╂	╃	╄	╅	╆	╇
╈	╉	╊	╋	╌	╍	╎	╏	═	║	╒	╓
╔	╕	╖	╗	╘	╙	╚	╛	╜	╝	╞	╟
╠	╡	╢	╣	╤	╥	╦	╧	╨
	╩	╪	╫ ╬	╭	╮	╯	╰	╱	╲
	╳	╴	╵	╶	╷ ╸	╹	╺	╻	╼	╽	╾╿
  
}
@endsalt