@startsalt
 
' Unicode characters don't scale but they 
' render more reliably and result in more 
' readable markup than sprites and 
' openiconic
' https://www.vertex42.com/ExcelTips/unicode-symbols.html

{+Unicode icons
  {
{
    🗀  ⚙
  ▁  🗔   🗙
  𝄘 ≡ ☰
  🗕  ⤓  ⤒  🔗  
  🝖 ▥ 
  	↩ ↪ ↶  ↷
  🡐 ⟳ ⌂ ⟰
  🛇 🛈  © ®
  ⏴ ⏵  ⏶  ⏷
   ⌨ ⌧ ⌦ ⏱
   ⧖ ⧗ 
  ⏭   ⏮    ⏯
  ▣ ◼ ☑ ▢ 
  ⦿  🔘☢ ◉
  ✂ ⎘  🛆
  }|
{
{    
  ← ↑ → ↓ 
  ↔ ↕ 
  ⇤ ⇥ ⤒ ⤓
  ↖ ↗ ↘ ↙ 
  ⤸ ⤹ ⤺ ⤻
  ⤴ ⤵ ⤶ ⤷	
☰ ☱ ☲ ☳	
☴ ☵ ☶ ☷
♺ ♻ ♼
⚐ <color:orange>⚑

𝄘 𝄙 𝄚 𝄛
}|
{

🕐 🕑 🕒   🕓 
🕔 🕕 🕖   🕗
🕘 🕙 🕚   🕛 
🕜 🕝 🕞   🕟
🕠 🕡 🕢   🕣
🕤 🕥 🕦   🕧
① ② ③ ④ 
  ⑤ ⑥ ⑦ ⑧ 
  ⑨ ⑩ ⑪ ⑫ 
  ⑬ ⑭ ⑮ ⑯ 
  ⑰ ⑱ ⑲ ⑳
  }
}
  }|
  {
  ❗❕  ❔  ❓  ⭐    ⭕
  🔁 🔃  📶   🔀  🔂   🔄
  🆕   ℹ️   ⚠️  ❌  ⛔ 💡
  🔓    🔒   🔑
    ⛔    ✅  ✨    ❎ ⭐
  ➕   ➖ 🟰
   🔔    🔕 ⌛

  ⌚    ⌛    🚩  🚫  🚀
  ⏩   ⏪   ⏫   ⏬
  🔎   🔍   🍳  📍    📌
  
  }|

}
@endsalt